project:
  type: website

website:
  title: "Andre Hiwatig"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - spacelab
      - brand
    css: styles.css
    toc: true

editor: visual

